version: '3.8'

services:
  dependency-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GitHubPat=<YOUR_PAT>
      - AzureDevopsPat=<YOUR_PAT>
      - TempDir=/dependency-tracker/tmp
      - OutputDir=/dependency-tracker/output
    volumes:
      - :/dependency-tracker/output
